const data = {
  products: [
    {
      // _id:'1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 1900,
      countInStock: 0,
      brand: 'Nike',
      rating: 2.8,
      numReviews: 108,
      description: 'high quality shirt',
    },
    {
      // _id:'2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 2500,
      countInStock: 2,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 458,
      description: 'high quality product',
    },
    {
      //_id:'3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 2100,
      countInStock: 15,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 163,
      description: 'high quality product',
    },
    {
      //_id:'4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 1650,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.6,
      numReviews: 89,
      description: 'high quality product',
    },
  ],
};
export default data;
